/**
 * BDIS - Bengkayang Distribution Intelligence System
 * PLN ULP Bengkayang - Demo Dataset
 * Strictly complying with gardu.prd specifications
 */

const BDIS_DATA = {
  regency: "Bengkayang",
  province: "Kalimantan Barat",
  unit: "PLN ULP Bengkayang",
  mapCenter: [0.8242, 109.6636], // Bengkayang City Center
  zoomLevel: 12,
  summary: {
    totalTrafos: 186,
    healthyPercentage: 91.4,
    activeAlerts: 12,
    mttrHours: 1.82,
    avgConditionIndex: 82.6,
    saidiHours: 4.21,
    saifiTimes: 3.12,
    caidiHours: 1.35,
    energyNotServedMWh: 14.8,
    riskDistribution: {
      normal: 142,   // Green
      waspada: 28,   // Yellow
      warning: 10,   // Orange
      critical: 6    // Red
    }
  },

  feeders: [
    { id: "F-KOTA", name: "Penyulang Kota", trafos: 54, lengthKm: 42.6, capacityKva: 8500, peakLoadPct: 76.4, status: "Normal" },
    { id: "F-TERIAK", name: "Penyulang Teriak", trafos: 41, lengthKm: 58.2, capacityKva: 6200, peakLoadPct: 84.1, status: "Warning" },
    { id: "F-SAMALANTAN", name: "Penyulang Samalantan", trafos: 36, lengthKm: 49.8, capacityKva: 5400, peakLoadPct: 68.9, status: "Normal" },
    { id: "F-SANGGAU_LEDO", name: "Penyulang Sanggau Ledo", trafos: 32, lengthKm: 64.3, capacityKva: 4800, peakLoadPct: 72.3, status: "Waspada" },
    { id: "F-JAGOI_BABANG", name: "Penyulang Jagoi Babang", trafos: 23, lengthKm: 78.5, capacityKva: 3600, peakLoadPct: 61.2, status: "Normal" }
  ],

  // Specific demo transformers as referenced in gardu.prd
  transformers: [
    {
      id: "TRF-BKY-004",
      name: "Gardu Distribusi Pasar Bengkayang",
      substation: "GI Bengkayang 150kV",
      feeder: "Penyulang Kota",
      region: "Bengkayang Kota",
      lat: 0.8258,
      lng: 109.6645,
      capacityKva: 250,
      commissioningYear: 2007,
      ageYears: 17,
      primaryVoltageKv: 20.0,
      secondaryVoltageV: 380,
      actualCurrentA: 395,
      loadKva: 260,
      loadingPct: 104.0,
      overloadDurationHours: 48.5,
      temperatureC: 81.2,
      voltageDeviationPct: 6.8,
      powerFactor: 0.69,
      outages12m: 7,
      trips12m: 5,
      maintenanceScore: 42,
      lastMaintenanceDays: 248,
      oilTestScore: 45,
      conditionIndex: 28,
      riskLevel: "CRITICAL",
      priority: "P1",
      topFactors: [
        "Overload berkepanjangan (104% kapasitas terpasang, durasi 48.5 jam)",
        "Suhu puncak mencapai 81.2°C memicu degradasi minyak trafo",
        "Power Factor sangat rendah (0.69)",
        "Tingkat gangguan tinggi (7 kali padam & 5 trip dalam 12 bulan)"
      ],
      recommendedAction: "P1 - Segera jadwalkan manuver beban darurat, inspeksi fisik DGA minyak trafo, dan uji tahanan isolasi dalam <48 jam.",
      probDeterioration90d: 78,
      notes: "Prioritas tertinggi penggantian kapasitas atau trafo sisipan"
    },
    {
      id: "TRF-BKY-023",
      name: "Gardu Distribusi Bumi Sebalo",
      substation: "GH Sebalo",
      feeder: "Penyulang Teriak",
      region: "Sebalo",
      lat: 0.8122,
      lng: 109.6450,
      capacityKva: 160,
      commissioningYear: 2012,
      ageYears: 12,
      primaryVoltageKv: 20.0,
      secondaryVoltageV: 380,
      actualCurrentA: 211,
      loadKva: 139.2,
      loadingPct: 87.0,
      overloadDurationHours: 24.0,
      temperatureC: 68.0,
      voltageDeviationPct: 4.9,
      powerFactor: 0.82,
      outages12m: 5,
      trips12m: 3,
      maintenanceScore: 58,
      lastMaintenanceDays: 165,
      oilTestScore: 61,
      conditionIndex: 42,
      riskLevel: "CRITICAL",
      priority: "P1",
      topFactors: [
        "Loading meningkat pesat (+14% dalam 3 bulan terakhir)",
        "Suhu operasi konsisten di atas rata-rata (68°C)",
        "Riwayat trip akibat sambaran petir di jalur ekspose"
      ],
      recommendedAction: "P1 - Pasang lightning arrester baru & jadwalkan inspeksi termovisi serta DGA dalam 7 hari.",
      probDeterioration90d: 54,
      notes: "Beban perumahan baru berkembang pesat di koridor Sebalo"
    },
    {
      id: "TRF-BKY-081",
      name: "Gardu Kantor Bupati Bengkayang",
      substation: "GI Bengkayang 150kV",
      feeder: "Penyulang Kota",
      region: "Pusat Pemerintahan",
      lat: 0.8412,
      lng: 109.6789,
      capacityKva: 315,
      commissioningYear: 2010,
      ageYears: 14,
      primaryVoltageKv: 20.0,
      secondaryVoltageV: 380,
      actualCurrentA: 440,
      loadKva: 289.8,
      loadingPct: 92.0,
      overloadDurationHours: 19.4,
      temperatureC: 72.5,
      voltageDeviationPct: 5.2,
      powerFactor: 0.77,
      outages12m: 4,
      trips12m: 3,
      maintenanceScore: 50,
      lastMaintenanceDays: 180,
      oilTestScore: 54,
      conditionIndex: 48,
      riskLevel: "CRITICAL",
      priority: "P1",
      topFactors: [
        "Ketidakseimbangan beban antar fasa mencapai 22%",
        "Beban puncak AC perkantoran sering melampaui 92%",
        "Kondisi isolasi minyak mulai mendekati ambang batas kritis"
      ],
      recommendedAction: "P1 - Penyeimbangan beban jurusan fasa R-S-T dan treatment purifikasi minyak trafo.",
      probDeterioration90d: 46,
      notes: "Aset vital pelayanan publik pemerintahan kabupaten"
    },
    {
      id: "TRF-BKY-044",
      name: "Gardu Distribusi Sinar Tebas",
      substation: "GH Samalantan",
      feeder: "Penyulang Samalantan",
      region: "Samalantan",
      lat: 0.7850,
      lng: 109.4580,
      capacityKva: 100,
      commissioningYear: 2014,
      ageYears: 10,
      primaryVoltageKv: 20.0,
      secondaryVoltageV: 380,
      actualCurrentA: 115,
      loadKva: 76.0,
      loadingPct: 76.0,
      overloadDurationHours: 8.2,
      temperatureC: 62.0,
      voltageDeviationPct: 3.8,
      powerFactor: 0.84,
      outages12m: 3,
      trips12m: 2,
      maintenanceScore: 66,
      lastMaintenanceDays: 112,
      oilTestScore: 68,
      conditionIndex: 57,
      riskLevel: "WARNING",
      priority: "P2",
      topFactors: [
        "Fluktuasi tegangan sekunder di ujung jaringan (+/- 3.8%)",
        "Jarak rambat vegetasi pohon kelapa sawit mendekati SUTM"
      ],
      recommendedAction: "P2 - ROW pemangkasan pohon di sekitar gardu dan setting tap changer.",
      probDeterioration90d: 31,
      notes: "Kawasan perkebunan dengan kelembapan tinggi"
    },
    {
      id: "TRF-BKY-052",
      name: "Gardu Teriak Sentral",
      substation: "GH Sebalo",
      feeder: "Penyulang Teriak",
      region: "Teriak",
      lat: 0.7680,
      lng: 109.5850,
      capacityKva: 160,
      commissioningYear: 2015,
      ageYears: 9,
      primaryVoltageKv: 20.0,
      secondaryVoltageV: 380,
      actualCurrentA: 185,
      loadKva: 121.6,
      loadingPct: 76.0,
      overloadDurationHours: 11.0,
      temperatureC: 64.5,
      voltageDeviationPct: 4.1,
      powerFactor: 0.81,
      outages12m: 4,
      trips12m: 2,
      maintenanceScore: 64,
      lastMaintenanceDays: 95,
      oilTestScore: 70,
      conditionIndex: 59,
      riskLevel: "WARNING",
      priority: "P2",
      topFactors: [
        "Beban malam hari mendekati ambang batas peringatan",
        "Tahanan pembumian (grounding) terukur 7.2 Ohm (di atas standar <5 Ohm)"
      ],
      recommendedAction: "P2 - Perbaikan elektroda grounding pembumian body dan arrester gardu.",
      probDeterioration90d: 28,
      notes: "Kecamatan Teriak sering terkena sambaran petir saat musim penghujan"
    },
    {
      id: "TRF-BKY-109",
      name: "Gardu Sanggau Ledo Pasar",
      substation: "GH Sanggau Ledo",
      feeder: "Penyulang Sanggau Ledo",
      region: "Sanggau Ledo",
      lat: 1.0340,
      lng: 109.8050,
      capacityKva: 200,
      commissioningYear: 2016,
      ageYears: 8,
      primaryVoltageKv: 20.0,
      secondaryVoltageV: 380,
      actualCurrentA: 194,
      loadKva: 128.0,
      loadingPct: 64.0,
      overloadDurationHours: 2.1,
      temperatureC: 56.4,
      voltageDeviationPct: 3.1,
      powerFactor: 0.88,
      outages12m: 2,
      trips12m: 1,
      maintenanceScore: 73,
      lastMaintenanceDays: 82,
      oilTestScore: 75,
      conditionIndex: 63,
      riskLevel: "WASPADA",
      priority: "P2",
      topFactors: [
        "Koneksi bushing sekunder mulai kusam (potensi hotspot)",
        "Beban pasar mingguan fluktuatif"
      ],
      recommendedAction: "P2 - Inspeksi termovisi pada jam beban puncak dan pengencangan konektor.",
      probDeterioration90d: 21,
      notes: "Pusat aktivitas perdagangan di utara Bengkayang"
    },
    {
      id: "TRF-BKY-067",
      name: "Gardu Ledo Perbatasan",
      substation: "GH Sanggau Ledo",
      feeder: "Penyulang Sanggau Ledo",
      region: "Ledo",
      lat: 0.9680,
      lng: 109.7340,
      capacityKva: 100,
      commissioningYear: 2017,
      ageYears: 7,
      primaryVoltageKv: 20.0,
      secondaryVoltageV: 380,
      actualCurrentA: 98,
      loadKva: 64.5,
      loadingPct: 64.5,
      overloadDurationHours: 1.5,
      temperatureC: 54.0,
      voltageDeviationPct: 2.9,
      powerFactor: 0.89,
      outages12m: 2,
      trips12m: 1,
      maintenanceScore: 75,
      lastMaintenanceDays: 70,
      oilTestScore: 78,
      conditionIndex: 68,
      riskLevel: "WASPADA",
      priority: "P3",
      topFactors: [
        "Usia operasional menengah, kondisi isolasi dan minyak stabil",
        "Riwayat gangguan ringan dari jaringan SUTM ranting"
      ],
      recommendedAction: "P3 - Jadwalkan pemeliharaan berkala triwulan berikutnya.",
      probDeterioration90d: 15,
      notes: "Jalur poros Bengkayang - Sambas"
    },
    {
      id: "TRF-BKY-017",
      name: "Gardu RSUD Bengkayang",
      substation: "GI Bengkayang 150kV",
      feeder: "Penyulang Kota",
      region: "Bengkayang Kota",
      lat: 0.8290,
      lng: 109.6710,
      capacityKva: 315,
      commissioningYear: 2020,
      ageYears: 4,
      primaryVoltageKv: 20.0,
      secondaryVoltageV: 380,
      actualCurrentA: 260,
      loadKva: 171.0,
      loadingPct: 54.3,
      overloadDurationHours: 0.0,
      temperatureC: 48.0,
      voltageDeviationPct: 1.4,
      powerFactor: 0.94,
      outages12m: 0,
      trips12m: 0,
      maintenanceScore: 92,
      lastMaintenanceDays: 35,
      oilTestScore: 94,
      conditionIndex: 84,
      riskLevel: "NORMAL",
      priority: "P3",
      topFactors: [
        "Peralatan prima, genset backup sinkron otomatis",
        "Loading optimum di kisaran 54%, suhu operasi sangat sejuk 48°C",
        "Power factor tinggi 0.94 dengan bank kapasitor aktif"
      ],
      recommendedAction: "P3 - Pertahankan jadwal pemeliharaan rutin preventif tahunan.",
      probDeterioration90d: 6,
      notes: "Pelanggan prioritas medis ULP Bengkayang"
    },
    {
      id: "TRF-BKY-001",
      name: "Gardu Induk Feeder Out Bengkayang",
      substation: "GI Bengkayang 150kV",
      feeder: "Penyulang Kota",
      region: "Bengkayang Kota",
      lat: 0.8350,
      lng: 109.6580,
      capacityKva: 400,
      commissioningYear: 2021,
      ageYears: 3,
      primaryVoltageKv: 20.0,
      secondaryVoltageV: 380,
      actualCurrentA: 290,
      loadKva: 190.8,
      loadingPct: 47.7,
      overloadDurationHours: 0.0,
      temperatureC: 45.2,
      voltageDeviationPct: 1.1,
      powerFactor: 0.96,
      outages12m: 0,
      trips12m: 0,
      maintenanceScore: 96,
      lastMaintenanceDays: 20,
      oilTestScore: 98,
      conditionIndex: 94,
      riskLevel: "NORMAL",
      priority: "P4",
      topFactors: [
        "Gardu baru dengan proteksi digital relay terkalibrasi",
        "Tidak ada histori gangguan dalam 12 bulan terakhir",
        "Minyak trafo dengan BDV > 65 kV"
      ],
      recommendedAction: "P4 - Pemeliharaan terjadwal reguler standar PLN.",
      probDeterioration90d: 3,
      notes: "Kondisi sangat sehat dan andal"
    },
    {
      id: "TRF-BKY-012",
      name: "Gardu Sebopet",
      substation: "GH Sebalo",
      feeder: "Penyulang Teriak",
      region: "Sebalo",
      lat: 0.7950,
      lng: 109.6100,
      capacityKva: 100,
      commissioningYear: 2019,
      ageYears: 5,
      primaryVoltageKv: 20.0,
      secondaryVoltageV: 380,
      actualCurrentA: 72,
      loadKva: 47.5,
      loadingPct: 47.5,
      overloadDurationHours: 0.0,
      temperatureC: 46.5,
      voltageDeviationPct: 1.8,
      powerFactor: 0.92,
      outages12m: 1,
      trips12m: 0,
      maintenanceScore: 89,
      lastMaintenanceDays: 45,
      oilTestScore: 90,
      conditionIndex: 88,
      riskLevel: "NORMAL",
      priority: "P4",
      topFactors: [
        "Beban moderat, suhu aman di bawah 50°C",
        "Grounding grounding terawat < 3.2 Ohm"
      ],
      recommendedAction: "P4 - Monitor kondisi secara rutin melalui inspeksi bulanan.",
      probDeterioration90d: 5,
      notes: "Kawasan pedesaan tenang"
    },
    {
      id: "TRF-BKY-035",
      name: "Gardu Cendrawasih",
      substation: "GI Bengkayang 150kV",
      feeder: "Penyulang Kota",
      region: "Bengkayang Kota",
      lat: 0.8210,
      lng: 109.6690,
      capacityKva: 200,
      commissioningYear: 2018,
      ageYears: 6,
      primaryVoltageKv: 20.0,
      secondaryVoltageV: 380,
      actualCurrentA: 155,
      loadKva: 102.0,
      loadingPct: 51.0,
      overloadDurationHours: 0.0,
      temperatureC: 49.0,
      voltageDeviationPct: 1.9,
      powerFactor: 0.91,
      outages12m: 1,
      trips12m: 0,
      maintenanceScore: 88,
      lastMaintenanceDays: 52,
      oilTestScore: 89,
      conditionIndex: 86,
      riskLevel: "NORMAL",
      priority: "P4",
      topFactors: [
        "Kondisi beban perumahan seimbang",
        "Tegangan pelayanan sesuai SPLN (220V +/- 5%)"
      ],
      recommendedAction: "P4 - Lanjutkan pemeliharaan preventif kuartalan.",
      probDeterioration90d: 7,
      notes: "Perumahan Cendrawasih Asri"
    },
    {
      id: "TRF-BKY-099",
      name: "Gardu Jagoi Babang PLBN",
      substation: "GH Jagoi Babang",
      feeder: "Penyulang Jagoi Babang",
      region: "Jagoi Babang",
      lat: 1.3320,
      lng: 109.9320,
      capacityKva: 315,
      commissioningYear: 2022,
      ageYears: 2,
      primaryVoltageKv: 20.0,
      secondaryVoltageV: 380,
      actualCurrentA: 210,
      loadKva: 138.6,
      loadingPct: 44.0,
      overloadDurationHours: 0.0,
      temperatureC: 43.8,
      voltageDeviationPct: 1.2,
      powerFactor: 0.95,
      outages12m: 0,
      trips12m: 0,
      maintenanceScore: 98,
      lastMaintenanceDays: 15,
      oilTestScore: 99,
      conditionIndex: 96,
      riskLevel: "NORMAL",
      priority: "P4",
      topFactors: [
        "Aset PLBN perbatasan RI-Malaysia berstandar tinggi",
        "Sistem proteksi SCADA terintegrasi",
        "Kondisi operasional sempurna"
      ],
      recommendedAction: "P4 - Pertahankan SLA keandalan kawasan strategis nasional.",
      probDeterioration90d: 2,
      notes: "Pos Lintas Batas Negara Jagoi Babang"
    }
  ],

  // Monthly Outage Trend Data for Bengkayang (Jan - Jun)
  monthlyOutages: [
    { month: "Jan", gangguan: 18, trip: 12, durasiJam: 24.5, saidi: 0.78, saifi: 0.58 },
    { month: "Feb", gangguan: 14, trip: 9,  durasiJam: 19.2, saidi: 0.62, saifi: 0.49 },
    { month: "Mar", gangguan: 22, trip: 15, durasiJam: 31.0, saidi: 1.05, saifi: 0.74 },
    { month: "Apr", gangguan: 16, trip: 10, durasiJam: 21.8, saidi: 0.71, saifi: 0.52 },
    { month: "Mei", gangguan: 11, trip: 7,  durasiJam: 14.6, saidi: 0.49, saifi: 0.38 },
    { month: "Jun", gangguan: 12, trip: 8,  durasiJam: 16.4, saidi: 0.56, saifi: 0.41 }
  ],

  // Outage Causes Breakdown
  outageCauses: [
    { cause: "Pohon & Senggolan Ranting (ROW)", percentage: 42, color: "#22c55e" },
    { cause: "Komponen & Trafo Overload", percentage: 28, color: "#ef4444" },
    { cause: "Gangguan Hewan (Kelelawar/Tupai)", percentage: 18, color: "#f59e0b" },
    { cause: "Sambaran Petir Ekstrem", percentage: 12, color: "#00a8ff" }
  ],

  // AI ANFIS Model Performance Comparison Benchmark (from PRD PROMPT 5)
  modelBenchmarks: [
    { model: "ANFIS (Adaptive Neuro-Fuzzy)", mae: "1.42", rmse: "2.18", r2: "0.964", status: "Optimal (Dipakai)", badge: "Champion" },
    { model: "Gradient Boosting / XGBoost", mae: "1.89", rmse: "2.64", r2: "0.938", status: "Sangat Baik", badge: "Runner-up" },
    { model: "Random Forest Regressor", mae: "2.21", rmse: "3.05", r2: "0.912", status: "Cukup Baik", badge: "Baseline" },
    { model: "MLP Neural Network", mae: "2.85", rmse: "3.78", r2: "0.879", status: "Sensitif Ukuran Data", badge: "Experimental" }
  ],

  // ANFIS Fuzzy Rule Base Samples
  fuzzyRules: [
    { rule: "R1", ifCondition: "Loading IS HIGH (>=90%) AND Temp IS HIGH (>=75°C) AND Trips IS HIGH", thenResult: "Condition IS CRITICAL (<35)", weight: 1.0 },
    { rule: "R2", ifCondition: "Loading IS HIGH (>=85%) AND PowerFactor IS LOW (<=0.75)", thenResult: "Condition IS WARNING (35-60)", weight: 0.9 },
    { rule: "R3", ifCondition: "Age IS OLD (>=15yr) AND OilScore IS LOW (<=50)", thenResult: "Condition IS CRITICAL (<40)", weight: 0.85 },
    { rule: "R4", ifCondition: "Loading IS NORMAL (<=65%) AND Temp IS NORMAL (<=55°C) AND Trips IS ZERO", thenResult: "Condition IS HEALTHY (>=85)", weight: 1.0 }
  ]
};

// Expose globally
window.BDIS_DATA = BDIS_DATA;
